### ISSUE TITLE
stampa riepiloghi interventi per ditta

### ISSUE THREAD

**Issue by marzekk** [scientificbear/gestionale_comune#13]
ciao
ti ricordi che dicevamo di inserire dei pulsanti per esportare o stampare la lista degli interventi per ogni ditta?

Pensi di poterlo fare a tempo perso o devo aprire ... il portafoglio!? :D

**Comment by scientificbear** [comment]
https://github.com/scientificbear/gestionale_comune/commit/2f25e9bb4094869334c16ee84edfacc246efe564
